version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prova
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - api

  api:
    image: api:latest
    build: .
    container_name: api
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - api

volumes:
  pgdata:

networks:
  api: